# syntax=docker/dockerfile:1

FROM python:3.9
RUN apt-get update && apt-get install -y ffmpeg poppler-utils libfile-mimeinfo-perl libimage-exiftool-perl ghostscript libsecret-1-0 zlib1g-dev libjpeg-dev imagemagick libmagic1 webp
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /up

COPY requirements.txt /up
RUN pip install -r requirements.txt
COPY . /up