version: "3.8"

services:
   app:
     build:
       context: ./up
       dockerfile: Dockerfile_app_dev
     command: npm run docker
     volumes:
       - /Users/thanford/PycharmProjects/Uprove/up:/up
       - /up/node_modules
     ports:
       - "3000:3000"
   backend:
     build:
       context: ./up
       dockerfile: Dockerfile_backend_dev
     command: bash -c "python manage.py collectstatic --noinput --clear && python manage.py runserver 0.0.0.0:8080"
     environment:
       IS_DOCKER: true
     depends_on:
       - db
       - app
     ports:
       - "8080:8080"
   db:
     restart: always
     image: postgres:14
     environment:
       POSTGRES_PASSWORD_FILE: /run/secrets/db_password
       POSTGRES_USER: todd
       POSTGRES_DB: uprove
     ports:
       - "5432"
     secrets:
       - db_password
     volumes:
       - uprove-db:/var/lib/postgresql/data

secrets:
  db_password:
    file: secrets/postgres_pwd

volumes:
  uprove-db:
  upapp:
