# Generated by Django 3.2.7 on 2021-10-02 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orgType', models.CharField(choices=[('company', 'company'), ('school', 'school')], max_length=30)),
                ('logo', models.ImageField(null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('name', models.CharField(max_length=75)),
                ('birthDate', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('isDefault', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('makePublic', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20, null=True)),
                ('profilePicture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.userimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('sectionOrder', models.SmallIntegerField()),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.userprofile')),
            ],
            options={
                'unique_together': {('userProfile', 'sectionOrder')},
            },
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg'])])),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('tagType', models.CharField(choices=[('interest', 'interest'), ('skill', 'skill')], max_length=25)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
                ('skillLevel', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'xls', 'xlsx', 'ppt', 'pptx', 'twb', 'twbx', 'pages', 'numbers', 'key', 'gdoc', 'gslides', 'gsheet'])])),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('positionTitle', models.CharField(max_length=100)),
                ('employmentType', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Contracted', 'Contracted'), ('Internship', 'Internship')], max_length=20)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('degree', models.CharField(choices=[('Associate of Arts', 'Associate of Arts'), ('Associate of Science', 'Associate of Science'), ('Associate of Applied Science', 'Associate of Applied Science'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Science', 'Bachelor of Science'), ('Master of Arts', 'Master of Arts'), ('Master of Science', 'Master of Science'), ('Master of Business Administration', 'Master of Business Administration'), ('Doctoral Degree', 'Doctoral Degree'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Juris Doctor', 'Juris Doctor')], max_length=50, null=True)),
                ('degreeSubject', models.CharField(max_length=200, null=True)),
                ('activities', models.TextField(null=True)),
                ('startDate', models.DateTimeField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upapp.user'),
        ),
        migrations.CreateModel(
            name='UserProfileSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentOrder', models.SmallIntegerField()),
                ('contentItemId', models.PositiveIntegerField()),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('userProfileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.userprofilesection')),
            ],
            options={
                'unique_together': {('userProfileSection', 'contentOrder')},
            },
        ),
        migrations.CreateModel(
            name='UserContentItemSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentOrder', models.SmallIntegerField()),
                ('userContentItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.usercontentitem')),
            ],
            options={
                'unique_together': {('userContentItem', 'contentOrder')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'orgType')},
        ),
    ]
