# Generated by Django 3.2.7 on 2021-10-09 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upapp', '0002_user_djangouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middleName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usercontentitemsection',
            name='contentItemId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usercontentitemsection',
            name='contentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usercontentitemsection',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profileName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='djangoUser',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercontentitem',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contentItem', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='usercontentitemsection',
            name='userContentItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='upapp.usercontentitem'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='userprofilesection',
            name='userProfile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='upapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofilesectionitem',
            name='contentItemId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofilesectionitem',
            name='contentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='userprofilesectionitem',
            name='userProfileSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionItem', to='upapp.userprofilesection'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='upapp.user'),
        ),
    ]
