# Generated by Django 3.2.7 on 2021-10-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0003_auto_20211009_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmployerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('companyEmployeeCount', models.CharField(max_length=10, null=True)),
                ('note', models.TextField(null=True)),
                ('hiringFunctions', models.ManyToManyField(null=True, to='upapp.ProjectFunction')),
                ('hiringSkills', models.ManyToManyField(null=True, to='upapp.ProjectSkill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
