# Generated by Django 3.2.7 on 2021-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0004_auto_20211024_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerinterest',
            name='modifiedDateTime',
        ),
        migrations.AlterField(
            model_name='employerinterest',
            name='hiringFunctions',
            field=models.ManyToManyField(to='upapp.ProjectFunction'),
        ),
        migrations.AlterField(
            model_name='employerinterest',
            name='hiringSkills',
            field=models.ManyToManyField(to='upapp.ProjectSkill'),
        ),
    ]
