# Generated by Django 3.2.7 on 2021-10-30 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0005_auto_20211030_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerinterest',
            name='modifiedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
