# Generated by Django 3.2.7 on 2021-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0006_employerinterest_modifieddatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedInProfile', models.CharField(max_length=100)),
                ('referrer', models.CharField(max_length=50, null=True)),
                ('note', models.TextField(null=True)),
                ('currentSkills', models.ManyToManyField(to='upapp.ProjectSkill')),
                ('interestedFunctions', models.ManyToManyField(to='upapp.ProjectFunction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
