# Generated by Django 3.2.7 on 2021-11-10 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0007_candidateinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('companyName', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(null=True, upload_to='logos-test/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('skillLevel', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('description', models.TextField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.employer')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.projectfunction')),
                ('skills', models.ManyToManyField(to='upapp.ProjectSkill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos-test/'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='uploads-candidate-test/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'xls', 'xlsx', 'ppt', 'pptx', 'twb', 'twbx', 'pages', 'numbers', 'key', 'gdoc', 'gslides', 'gsheet'])]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='uploads-candidate-test/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.FileField(upload_to='uploads-candidate-test/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg'])]),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='uploads-project-test/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
