# Generated by Django 3.2.7 on 2021-11-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0008_auto_20211110_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
