# Generated by Django 3.2.7 on 2021-11-18 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0009_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userTypeBits',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='upapp.employer'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectFile', to='upapp.project'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='upapp.user'),
        ),
    ]
