# Generated by Django 3.2.7 on 2021-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0010_auto_20211118_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skillLevel',
        ),
        migrations.AddField(
            model_name='project',
            name='skillLevelBits',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='skillLevel',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (4, 4), (8, 8)], null=True),
        ),
    ]
