# Generated by Django 3.2.7 on 2021-11-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0011_auto_20211120_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='upapp.employer'),
        ),
    ]
