# Generated by Django 3.2.7 on 2021-11-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0012_user_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads-project-test/'),
        ),
    ]
