# Generated by Django 3.2.7 on 2021-12-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0015_auto_20211202_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinstructions',
            unique_together={('project', 'skillLevelBit')},
        ),
        migrations.CreateModel(
            name='EmployerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(null=True)),
                ('skillLevelBit', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employerProject', to='upapp.project')),
                ('skills', models.ManyToManyField(to='upapp.ProjectSkill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('jobTitle', models.CharField(max_length=100)),
                ('jobDescription', models.TextField()),
                ('openDate', models.DateField(null=True)),
                ('pauseDate', models.DateField(null=True)),
                ('closeDate', models.DateField(null=True)),
                ('salaryFloor', models.FloatField(null=True)),
                ('salaryCeiling', models.FloatField(null=True)),
                ('salaryUnit', models.CharField(max_length=25, null=True)),
                ('allowedProjects', models.ManyToManyField(related_name='employerJobProjects', to='upapp.EmployerProject')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employerJob', to='upapp.employer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
