# Generated by Django 3.2.7 on 2021-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0016_auto_20211206_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjob',
            name='allowedProjects',
        ),
    ]
