# Generated by Django 3.2.7 on 2021-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0018_remove_employerjob_allowedprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('skillLevelBit', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customProject', to='upapp.project')),
                ('skills', models.ManyToManyField(to='upapp.ProjectSkill')),
            ],
            options={
                'unique_together': {('project', 'skillLevelBit')},
            },
        ),
        migrations.CreateModel(
            name='UserJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteDateTime', models.DateTimeField(null=True)),
                ('submissionDateTime', models.DateTimeField(null=True)),
                ('approveDateTime', models.DateTimeField(null=True)),
                ('declineDateTime', models.DateTimeField(null=True)),
                ('employerJob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobApplication', to='upapp.employerjob')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('customProject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.customproject')),
                ('files', models.ManyToManyField(to='upapp.UserFile')),
                ('images', models.ManyToManyField(to='upapp.UserImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.user')),
                ('videos', models.ManyToManyField(to='upapp.UserVideo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmployerProject',
        ),
        migrations.AddField(
            model_name='userjobapplication',
            name='userProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.userproject'),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='allowedProjects',
            field=models.ManyToManyField(related_name='employerJobProjects', to='upapp.CustomProject'),
        ),
    ]
