# Generated by Django 3.2.7 on 2021-12-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0019_auto_20211219_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproject',
            name='createdDateTime',
        ),
        migrations.RemoveField(
            model_name='customproject',
            name='modifiedDateTime',
        ),
    ]
