# Generated by Django 3.2.7 on 2022-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0022_alter_blogtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'customProject')},
        ),
    ]
