# Generated by Django 3.2.7 on 2022-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0023_auto_20220103_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobapplication',
            name='withdrawDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='projectNotes',
            field=models.TextField(null=True),
        ),
    ]
