# Generated by Django 3.2.7 on 2022-01-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0025_projectskill_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100, null=True)),
                ('skillLevelBits', models.SmallIntegerField(default=1)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upapp.employer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationCriteria', to='upapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerCustomProjectCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.customproject')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.employer')),
                ('evaluationCriterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.projectevaluationcriterion')),
            ],
        ),
    ]
