# Generated by Django 3.2.7 on 2022-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0026_employercustomprojectcriterion_projectevaluationcriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevaluationcriterion',
            name='skillLevelBits',
            field=models.SmallIntegerField(null=True),
        ),
    ]
