# Generated by Django 3.2.7 on 2022-01-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0028_alter_projectevaluationcriterion_criterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectEvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.employer')),
                ('evaluationCriterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.projectevaluationcriterion')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
                ('userProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.userproject')),
            ],
        ),
    ]
