# Generated by Django 3.2.7 on 2022-01-06 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0029_userprojectevaluationcriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectevaluationcriterion',
            name='createdDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 32, 52, 169410)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectevaluationcriterion',
            name='modifiedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 33, 0, 616700)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprojectevaluationcriterion',
            name='userProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProjectEvaluationCriterion', to='upapp.userproject'),
        ),
    ]
