# Generated by Django 3.2.7 on 2022-01-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0030_auto_20220106_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjobapplication',
            unique_together={('userProject', 'employerJob')},
        ),
        migrations.AlterUniqueTogether(
            name='userprojectevaluationcriterion',
            unique_together={('userProject', 'evaluator', 'evaluationCriterion')},
        ),
    ]
