# Generated by Django 3.2.7 on 2022-01-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0031_auto_20220106_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerinterest',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
