# Generated by Django 3.2.7 on 2022-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0032_alter_employerinterest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='isDemo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isDemo',
            field=models.BooleanField(default=False),
        ),
    ]
