# Generated by Django 3.2.7 on 2022-01-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0033_auto_20220110_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
