# Generated by Django 3.2.7 on 2022-01-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0034_jobtemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customproject',
            unique_together=set(),
        ),
    ]
