# Generated by Django 3.2.7 on 2022-01-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0036_auto_20220125_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inviteEmployer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviteEmployer', to='upapp.employer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.employer'),
        ),
    ]
