# Generated by Django 3.2.7 on 2022-01-26 22:42
from upapp.migrations import executeSqlMigration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0037_auto_20220126_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerinterest',
            name='companyEmployeeCount',
        ),
        migrations.RemoveField(
            model_name='employerinterest',
            name='hiringFunctions',
        ),
        migrations.RemoveField(
            model_name='employerinterest',
            name='hiringSkills',
        ),
        migrations.RemoveField(
            model_name='employerinterest',
            name='title',
        ),
        migrations.RunPython(lambda apps, schemaEditor: executeSqlMigration('0038.sql'), atomic=True)
    ]
