# Generated by Django 3.2.7 on 2022-01-26 23:31

from django.db import migrations

from upapp.migrations import executeSqlMigration


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0038_auto_20220126_1742'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schemaEditor: executeSqlMigration('0039.sql'), atomic=True)
    ]
