# Generated by Django 3.2.7 on 2022-01-26 23:37

from django.db import migrations, models
import django.db.models.deletion

from upapp.migrations import executeSqlMigration


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0039_auto_20220126_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='function',
        # ),
        # migrations.DeleteModel(
        #     name='CandidateInterest',
        # ),
        # migrations.DeleteModel(
        #     name='ProjectFunction',
        # ),
        migrations.RunPython(lambda apps, schemaEditor: executeSqlMigration('0040.sql'), atomic=True),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='upapp.role'),
            preserve_default=False,
        ),
    ]
