# Generated by Django 3.2.7 on 2022-01-27 17:49

from django.db import migrations, models

from upapp.migrations import executeSqlMigration


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0040_fake_20220126_1837'),
    ]

    operations = [
        # migrations.RenameModel('ProjectSkill', 'Skill'),
        # migrations.RenameField('Skill', 'skillName', 'name'),
        # migrations.AlterField(
        #     model_name='customproject',
        #     name='skills',
        #     field=models.ManyToManyField(to='upapp.Skill'),
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='skills',
        #     field=models.ManyToManyField(to='upapp.Skill'),
        # ),
        # migrations.RunPython(lambda x, y: executeSqlMigration('0041.sql'), atomic=True)
    ]
