# Generated by Django 3.2.7 on 2022-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0042_fake_20220127_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='makePublic',
            field=models.BooleanField(default=True),
        ),
    ]
