# Generated by Django 3.2.7 on 2022-02-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0043_alter_userprofile_makepublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrimary',
            field=models.BooleanField(default=True),
        ),
    ]
