# Generated by Django 3.2.7 on 2022-02-15 21:49

import django.core.validators
from django.db import migrations, models
import upapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0044_userprofile_isprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=upapp.models.getUserUploadLocation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'xls', 'xlsx', 'ppt', 'pptx', 'twb', 'twbx', 'pages', 'numbers', 'key', 'gdoc', 'gslides', 'gsheet'])]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=upapp.models.getUserUploadLocation),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.FileField(upload_to=upapp.models.getUserUploadLocation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg'])]),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilesectionitem',
            unique_together=set(),
        ),
    ]
