# Generated by Django 3.2.7 on 2022-02-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0045_auto_20220215_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilesection',
            unique_together=set(),
        ),
    ]
