# Generated by Django 3.2.7 on 2022-02-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0046_alter_userprofilesection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProject', to='upapp.user'),
        ),
    ]
