# Generated by Django 3.2.7 on 2022-02-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0047_auto_20220218_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('interest', 'interest'), ('skill', 'skill')], max_length=25)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usertag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upapp.tag'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag')},
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='tagType',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='title',
        ),
    ]
