# Generated by Django 3.2.7 on 2022-02-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0048_auto_20220218_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertag',
            old_name='skillLevel',
            new_name='skillLevelBit',
        ),
    ]
