# Generated by Django 3.2.7 on 2022-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0051_auto_20220221_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileName',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(default='draft', max_length=8),
        ),
    ]
