# Generated by Django 3.2.7 on 2022-02-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0052_auto_20220222_1149'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                DELETE FROM upapp_userjobapplication uj1
                USING 
                    upapp_userproject proj1,
                    upapp_userproject proj2,
                    upapp_userjobapplication uj2
                WHERE 
                    uj1."userProject_id" = proj1.id
                    and proj1.user_id = proj2.user_id and proj1.id != proj2.id
                    and uj2."userProject_id" = proj2.id and uj2.id != uj1.id
                    and uj2.id > uj1.id;
            '''
        ),
        migrations.AddField(
            model_name='userjobapplication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjobapplication',
            name='userProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.userproject'),
        ),
        migrations.AlterUniqueTogether(
            name='userjobapplication',
            unique_together={('user', 'employerJob')},
        ),
        migrations.RunSQL(
            '''
                UPDATE upapp_userjobapplication as uj
                SET user_id = proj.user_id
                FROM upapp_userproject proj 
                WHERE uj."userProject_id" = proj.id;
            '''
        )
    ]
