# Generated by Django 3.2.7 on 2022-02-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0054_alter_userjobapplication_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField()),
                ('modifiedDateTime', models.DateTimeField()),
                ('hasExpiration', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('issueDate', models.DateField()),
                ('expirationDate', models.DateField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upapp.organization')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='upapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
