# Generated by Django 3.2.7 on 2022-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0058_auto_20220321_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='applicationUrl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='isScraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='jobDepartment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employerjob',
            unique_together={('employer', 'jobTitle', 'location')},
        ),
    ]
