# Generated by Django 3.2.7 on 2022-03-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0058_auto_20220321_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('waitlistType', models.CharField(max_length=100)),
                ('signUpDateTime', models.DateTimeField()),
            ],
        ),
    ]
