# Generated by Django 3.2.7 on 2022-04-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0059_auto_20220325_1055'),
        ('upapp', '0059_waitlist'),
    ]

    operations = [
    ]
