# Generated by Django 3.2.7 on 2022-04-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0060_merge_0059_auto_20220325_1055_0059_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectevaluationcriterion',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upapp.employer'),
        ),
    ]
