# Generated by Django 3.2.7 on 2022-03-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0060_merge_0059_auto_20220325_1055_0059_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='isRemote',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employerjob',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
