# Generated by Django 3.2.7 on 2022-04-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0062_employerjob_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='glassDoorUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
