# Generated by Django 3.2.7 on 2022-04-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0061_alter_userprojectevaluationcriterion_employer'),
        ('upapp', '0063_employer_glassdoorurl'),
    ]

    operations = [
    ]
