# Generated by Django 3.2.7 on 2022-04-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0064_merge_20220406_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companySize', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleTitle', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preferenceRemote',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenceCompanySizes',
            field=models.ManyToManyField(null=True, to='upapp.CompanySize'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenceCountry',
            field=models.ManyToManyField(null=True, to='upapp.Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenceRoles',
            field=models.ManyToManyField(null=True, to='upapp.RoleTitle'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenceState',
            field=models.ManyToManyField(null=True, to='upapp.State'),
        ),
    ]
