# Generated by Django 3.2.7 on 2022-04-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0065_auto_20220406_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='companySize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.companysize'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceCompanySizes',
            field=models.ManyToManyField(to='upapp.CompanySize'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceCountry',
            field=models.ManyToManyField(to='upapp.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceRemote',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceRoles',
            field=models.ManyToManyField(to='upapp.RoleTitle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceState',
            field=models.ManyToManyField(to='upapp.State'),
        ),
    ]
