# Generated by Django 3.2.7 on 2022-04-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0066_auto_20220407_1457'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                update upapp_employerjob
                set country = null, role = null, state= null;
            '''
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.country'),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.roletitle'),
        ),
        migrations.AlterField(
            model_name='employerjob',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.state'),
        ),
    ]
