# Generated by Django 3.2.7 on 2022-04-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0067_auto_20220407_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferenceRemote',
            new_name='preferenceRemoteBits',
        ),
    ]
