# Generated by Django 3.2.7 on 2022-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0069_auto_20220412_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='leverAccessToken',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='leverRefreshToken',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
