# Generated by Django 3.2.7 on 2022-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0070_auto_20220413_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='leverAccessToken',
            field=models.CharField(max_length=1400, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='leverRefreshToken',
            field=models.CharField(max_length=1400, null=True),
        ),
    ]
