# Generated by Django 3.2.7 on 2022-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0071_auto_20220413_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='leverTriggerStageKey',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
