# Generated by Django 3.2.7 on 2022-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0072_employer_levertriggerstagekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='leverCompleteStageKey',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
