# Generated by Django 3.2.7 on 2022-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0073_employer_levercompletestagekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='leverPostingKey',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
