# Generated by Django 3.2.7 on 2022-04-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0074_employerjob_leverpostingkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='isInternal',
            field=models.BooleanField(default=False),
        ),
    ]
