# Generated by Django 3.2.7 on 2022-04-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0076_userjobapplication_leveropportunitykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobapplication',
            name='hireDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
