# Generated by Django 3.2.7 on 2022-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0078_user_leveruserkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerjob',
            name='isFullTime',
            field=models.BooleanField(default=True),
        ),
    ]
