# Generated by Django 3.2.7 on 2022-04-22 22:08

from django.db import migrations, models
import upapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0080_part2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesection',
            name='title',
        ),
        migrations.AddField(
            model_name='userfile',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=upapp.models.getUserUploadLocation),
        ),
        migrations.AlterField(
            model_name='userprofilesection',
            name='sectionType',
            field=models.CharField(default='PROJECTS', max_length=15),
            preserve_default=False,
        ),
    ]
