# Generated by Django 3.2.7 on 2022-04-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0081_auto_20220422_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
