# Generated by Django 3.2.7 on 2022-04-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0082_auto_20220425_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceCountry',
            field=models.ManyToManyField(related_name='preferenceCountry', to='upapp.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferenceState',
            field=models.ManyToManyField(related_name='preferenceState', to='upapp.State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.state'),
        ),
    ]
