# Generated by Django 3.2.7 on 2022-05-04 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import upapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0083_auto_20220425_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercustomprojectcriterion',
            name='customProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employerCustomCriterion', to='upapp.customproject'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.FileField(upload_to=upapp.models.getUserUploadLocation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4v', 'mov', 'wmv', 'avi', 'mpg', 'webm'])]),
        ),
        migrations.CreateModel(
            name='EmployerCandidateFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upapp.user')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateFavorite', to='upapp.employer')),
                ('jobs', models.ManyToManyField(to='upapp.EmployerJob')),
            ],
            options={
                'unique_together': {('employer', 'candidate')},
            },
        ),
    ]
