# Generated by Django 3.2.7 on 2022-05-06 19:53

from django.db import migrations
from upapp.models import RoleLevel, User, EmployerJob


def consolidateRoles(_x, _y):
    roleLevels = {r.roleTitle: r.id for r in RoleLevel.objects.all()}
    roleMap = {}
    roleMap[roleLevels['Data engineering manager']] = roleLevels['Data analytics leader']
    roleMap[roleLevels['Data engineer']] = roleLevels['Data analyst']

    for user in User.objects.prefetch_related('preferenceRoles').all():
        for pref in user.preferenceRoles.all():
            if pref.roleTitle in roleMap:
                user.remove(pref)
                user.add(roleMap[pref.roleTitle])

    for job in EmployerJob.objects.select_related('roleLevel').all():
        if job.roleLevel and job.roleLevel.roleTitle in roleMap:
            job.roleLevel_id = roleMap[job.roleLevel.roleTitle]
            job.save()

    RoleLevel.objects.filter(roleTitle__in=['Data engineering manager', 'Data engineer']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0085_auto_20220506_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerjob',
            old_name='role',
            new_name='roleLevel',
        ),
        # migrations.RunPython(consolidateRoles)
    ]
