# Generated by Django 3.2.7 on 2022-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0087_alter_rolelevel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='isClient',
            field=models.BooleanField(default=False),
        ),
    ]
