# Generated by Django 3.2.7 on 2022-05-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0088_employer_isclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerjob',
            options={'ordering': ('-employer__isClient',)},
        ),
    ]
