# Generated by Django 3.2.7 on 2022-05-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0089_alter_employerjob_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerjob',
            options={'ordering': ('-employer__isClient', '-openDate')},
        ),
    ]
