# Generated by Django 3.2.7 on 2022-05-08 18:28

from django.db import migrations

from upapp.models import ProjectEvaluationCriterion, UserProjectEvaluationCriterion


def standardizeEvaluationCriterion(_x, _y):
    groupedCriterion = {(pec.project_id, pec.criterion): pec for pec in ProjectEvaluationCriterion.objects.all()}

    for userCriterion in UserProjectEvaluationCriterion.objects.select_related('evaluationCriterion').all():
        criterion = userCriterion.evaluationCriterion
        standardizedCriterion = groupedCriterion[(criterion.project_id, criterion.criterion)]
        userCriterion.evaluationCriterion = standardizedCriterion
        userCriterion.save()

    for criterion in ProjectEvaluationCriterion.objects.all():
        standardizedCriterion = groupedCriterion[(criterion.project_id, criterion.criterion)]
        if criterion.id != standardizedCriterion.id:
            criterion.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0090_alter_employerjob_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerCustomProjectCriterion',
        ),
        migrations.RunPython(standardizeEvaluationCriterion),
        migrations.RemoveField(
            model_name='projectevaluationcriterion',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='projectevaluationcriterion',
            name='skillLevelBits',
        ),
    ]
