# Generated by Django 3.2.7 on 2022-05-08 23:21

from django.db import migrations, models

# from upapp.models import ProjectInstructions, Project


# def moveInstructions(_x, _y):
#     consolidatedInstructions = {}
#     for instructions in ProjectInstructions.objects.all():
#         if not (existingInstructions := consolidatedInstructions.get(instructions.project_id)):
#             consolidatedInstructions[instructions.project_id] = instructions
#         elif existingInstructions.skillLevelBit < instructions.skillLevelBit:
#             consolidatedInstructions[instructions.project_id] = instructions
#
#     for project in Project.objects.all():
#         project.instructions = consolidatedInstructions.get(project.id).instructions
#         project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0091_standardizeProjectEvaluationCriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(null=True),
        ),
        # migrations.RunPython(moveInstructions)
    ]
