# Generated by Django 3.2.7 on 2022-05-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0092_project_instructions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInstructions',
        ),
    ]
