# Generated by Django 3.2.7 on 2022-05-09 19:10

from django.db import migrations

from upapp.models import ProjectFile

def consolidateProjectFiles(_x, _y):
    consolidatedFiles = {}
    for file in ProjectFile.objects.all():
        fileKey = (file.project_id, file.title)
        if existingFile := consolidatedFiles.get(fileKey):
            if file.skillLevelBits > existingFile.skillLevelBits:
                consolidatedFiles[fileKey] = file
        else:
            consolidatedFiles[fileKey] = file

    fileIdsToDelete = set()
    for file in ProjectFile.objects.all():
        fileKey = (file.project_id, file.title)
        if consolidatedFiles.get(fileKey).skillLevelBits != file.skillLevelBits:
            fileIdsToDelete.add(file.id)

    ProjectFile.objects.filter(id__in=fileIdsToDelete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0094_consolidateCustomProjects'),
    ]

    operations = [
        migrations.RunPython(consolidateProjectFiles),
    ]
