# Generated by Django 3.2.7 on 2022-05-09 20:10

from django.db import migrations

from upapp.models import Project


def updateProjectSkillLevel(_x, _y):
    for project in Project.objects.all():
        project.skillLevelBit = 1
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0095_remove_projectfile_skilllevelbits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skillLevelBits',
            new_name='skillLevelBit',
        ),
        migrations.RunPython(updateProjectSkillLevel)
    ]
