# Generated by Django 3.2.7 on 2022-05-11 17:10

from django.db import migrations
from django.db.models import Q

from upapp.migrations import executeSqlMigration
from upapp.models import Skill


def consolidateSkills(_x, _y):
    consolidatedSkills = {}
    for skill in Skill.objects.all():
        skillKey = (skill.name, skill.skillProject_id)
        if skillKey not in consolidatedSkills:
            consolidatedSkills[skillKey] = skill
        elif consolidatedSkills[skillKey].skillLevelBits < skill.skillLevelBits:
            consolidatedSkills[skillKey] = skill

    deleteFilter = ~Q(id__in=[s.id for s in consolidatedSkills.values()])
    Skill.objects.filter(deleteFilter).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0096_rename_skilllevelbits_project_skilllevelbit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='isRecommended',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='isRequired',
        ),
        # migrations.RunPython(consolidateSkills)
    ]
