# Generated by Django 3.2.7 on 2022-05-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0097_auto_20220511_1310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'skillProject')},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skillLevelBits',
        ),
    ]
