# Generated by Django 3.2.7 on 2022-05-11 19:17

import django.core.validators
from django.db import migrations, models
import upapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0098_auto_20220511_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to=upapp.models.getUserUploadLocation, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
    ]
