# Generated by Django 3.2.7 on 2022-05-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0099_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='skillLevelBits',
        ),
    ]
