# Generated by Django 3.2.7 on 2022-05-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0100_remove_projectfile_skilllevelbits'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='function',
        # ),
        migrations.AddField(
            model_name='user',
            name='preferenceSalary',
            field=models.IntegerField(null=True),
        ),
        # migrations.DeleteModel(
        #     name='ProjectFunction',
        # ),
    ]
