# Generated by Django 3.2.7 on 2022-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0102_auto_20220601_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='function',
        ),
        migrations.DeleteModel(
            name='ProjectFunction',
        ),
    ]
