# Generated by Django 3.2.7 on 2022-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0101_auto_20220531_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skillLevelBit',
        ),
    ]
