# Generated by Django 3.2.7 on 2022-06-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0102_fake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTemplate',
        ),
    ]
