# Generated by Django 3.2.7 on 2022-06-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0103_delete_jobtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobapplication',
            name='userProject',
        ),
    ]
