# Generated by Django 3.2.7 on 2022-06-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0105_auto_20220602_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesectionitem',
            name='contentOrder',
        ),
    ]
