# Generated by Django 3.2.7 on 2022-06-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0108_auto_20220606_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerjob',
            name='salaryUnit',
        ),
    ]
