# Generated by Django 3.2.7 on 2022-06-11 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0110_trainingcourse_usertraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='pricePremium',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='coverImage',
            field=models.ImageField(default='', upload_to='uploads-course-test/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='teachableCourseId',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertraining',
            name='completedDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='enrolledDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
