# Generated by Django 3.2.7 on 2022-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0111_auto_20220610_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobapplication',
            name='isExternal',
            field=models.BooleanField(default=True),
        ),
    ]
