# Generated by Django 3.2.7 on 2022-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0112_userjobapplication_isexternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
