# Generated by Django 3.2.7 on 2022-06-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0114_auto_20220612_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='urlCoursePage',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='urlSalesPage',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='salesPageSlug',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
