# Generated by Django 3.2.7 on 2022-06-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0116_auto_20220613_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraining',
            name='user',
        ),
        migrations.AddField(
            model_name='teachableuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachableUser', to='upapp.user'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='teachableUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userTraining', to='upapp.teachableuser'),
        ),
    ]
