# Generated by Django 3.2.7 on 2022-06-13 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0117_auto_20220613_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachableuser',
            name='createdDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
