# Generated by Django 3.2.7 on 2022-06-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0118_teachableuser_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachableuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upapp.user'),
        ),
    ]
