# Generated by Django 3.2.7 on 2022-06-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0119_alter_teachableuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='certificateImage',
            field=models.ImageField(default='', upload_to='uploads-course-test/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachableuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachableUser', to='upapp.user'),
        ),
    ]
