LOCATIONS = {
    'Amsterdam': {'isRemote': 0, 'city': 'Amsterdam', 'state': None, 'country': 'Netherlands', 'region': None},
    'Atlanta, Georgia': {'isRemote': 0, 'city': 'Atlanta', 'state': 'Georgia', 'country': 'USA', 'region': None},
    'Atlanta, GA': {'isRemote': 0, 'city': 'Atlanta', 'state': 'Georgia', 'country': 'USA', 'region': None},
    'Atlanta': {'isRemote': 0, 'city': 'Atlanta', 'state': 'Georgia', 'country': 'USA', 'region': None},
    'Auckland': {'isRemote': 0, 'city': 'Auckland', 'state': None, 'country': 'New Zealand', 'region': None},
    'Aurora': {'isRemote': 0, 'city': 'Aurora', 'state': 'Colorado', 'country': 'USA', 'region': None},
    'Austin, Texas': {'isRemote': 0, 'city': 'Austin', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Baltimore, Maryland': {'isRemote': 0, 'city': 'Baltimore', 'state': 'Maryland', 'country': 'USA', 'region': None},
    'Bangalore': {'isRemote': 0, 'city': 'Bangalore', 'state': None, 'country': 'India', 'region': None},
    'Carrer Pau Claris 190 Barcelona': {'isRemote': 0, 'city': 'Barcelona', 'state': None, 'country': 'Spain', 'region': None},
    'Beijing, China': {'isRemote': 0, 'city': 'Beijing', 'state': None, 'country': 'China', 'region': None},
    'belgrade, Serbia': {'isRemote': 0, 'city': 'Belgrade', 'state': None, 'country': 'Serbia', 'region': None},
    'Belgrade, Serbia': {'isRemote': 0, 'city': 'Belgrade', 'state': None, 'country': 'Serbia', 'region': None},
    'Boston, Massachusetts': {'isRemote': 0, 'city': 'Boston', 'state': 'Massachusetts', 'country': 'USA', 'region': None},
    'Boston, MA': {'isRemote': 0, 'city': 'Boston', 'state': 'Massachusetts', 'country': 'USA', 'region': None},
    'Remote - Brisbane': {'isRemote': 1, 'city': 'Brisbane', 'state': None, 'country': 'Australia', 'region': 'Brisbane'},
    'Brooklyn, New York': {'isRemote': 0, 'city': 'Brooklyn', 'state': 'New York', 'country': 'USA', 'region': None},
    'quip HQ': {'isRemote': 0, 'city': 'Brooklyn', 'state': 'New York', 'country': 'USA', 'region': None},
    'Brooklyn. NY': {'isRemote': 0, 'city': 'Brooklyn', 'state': 'New York', 'country': 'USA', 'region': None},
    'Brooklyn, NY': {'isRemote': 0, 'city': 'Brooklyn', 'state': 'New York', 'country': 'USA', 'region': None},
    'Buffalo, New York': {'isRemote': 0, 'city': 'Buffalo', 'state': 'New York', 'country': 'USA', 'region': None},
    'Chennai': {'isRemote': 0, 'city': 'Chennai', 'state': None, 'country': 'India', 'region': None},
    'Chicago': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Chicago, USA': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Chicago, Illinois': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Chicago, Illinois, United States': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Chicago, IL': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Chicago, West Loop': {'isRemote': 0, 'city': 'Chicago', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Cluj-Napoca, Cluj, Romania': {'isRemote': 0, 'city': 'Cluj-Napoca', 'state': None, 'country': 'Romania', 'region': None},
    'Columbus, Ohio': {'isRemote': 0, 'city': 'Columbus', 'state': 'Ohio', 'country': 'USA', 'region': None},
    'Crown Heights, New York': {'isRemote': 0, 'city': 'Crown Heights', 'state': 'New York', 'country': 'USA', 'region': None},
    'Dallas, TX': {'isRemote': 0, 'city': 'Dallas', 'state': 'Texas', 'country': None, 'region': None},
    'Dallas': {'isRemote': 0, 'city': 'Dallas', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Dallas, Texas': {'isRemote': 0, 'city': 'Dallas', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Delhi': {'isRemote': 0, 'city': 'Delhi', 'state': None, 'country': 'India', 'region': None},
    'Denver, Colorado': {'isRemote': 0, 'city': 'Denver', 'state': 'Colorado', 'country': 'USA', 'region': None},
    'Denver, CO': {'isRemote': 0, 'city': 'Denver', 'state': 'CO', 'country': None, 'region': None},
    'Denver': {'isRemote': 0, 'city': 'Denver', 'state': 'Colorado', 'country': 'USA', 'region': None},
    'Detroit, Michigan': {'isRemote': 0, 'city': 'Detroit', 'state': 'Michigan', 'country': 'USA', 'region': None},
    'Park Offices Drive, Durham, NC 27709': {'isRemote': 0, 'city': 'Durham', 'state': 'North Carolina', 'country': 'USA', 'region': None},
    'El Paso, Texas': {'isRemote': 0, 'city': 'El Paso', 'state': 'Texas', 'country': 'USA', 'region': None},
    'El Segundo, California': {'isRemote': 0, 'city': 'El Segundo', 'state': 'California', 'country': 'USA', 'region': None},
    'Evanston, Illinois': {'isRemote': 0, 'city': 'Evanston', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Fredericksburg, Virginia': {'isRemote': 0, 'city': 'Fredericksburg', 'state': 'Virginia', 'country': 'USA', 'region': None},
    'Glendale, CA': {'isRemote': 0, 'city': 'Glendale', 'state': 'California', 'country': 'USA', 'region': None},
    'Hoffman Estates, IL': {'isRemote': 0, 'city': 'Hoffman Estates', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Houston, Texas': {'isRemote': 0, 'city': 'Houston', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Houston': {'isRemote': 0, 'city': 'Houston', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Houston, TX': {'isRemote': 0, 'city': 'Houston', 'state': 'Texas', 'country': 'USA', 'region': None},
    'Indianapolis, IN': {'isRemote': 0, 'city': 'Indianapolis', 'state': 'Indiana', 'country': 'USA', 'region': None},
    'Irvine, California': {'isRemote': 0, 'city': 'Irvine', 'state': 'California', 'country': 'USA', 'region': None},
    'Istanbul, Istanbul, Turkey': {'isRemote': 0, 'city': 'Istanbul', 'state': None, 'country': 'Turkey', 'region': None},
    'Jacksonville, Florida': {'isRemote': 0, 'city': 'Jacksonville', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Jersey City, New Jersey, United States': {'isRemote': 0, 'city': 'Jersey City', 'state': 'New Jersey', 'country': 'USA', 'region': None},
    'Kansas City, Missouri': {'isRemote': 0, 'city': 'Kansas City', 'state': 'Missouri', 'country': 'USA', 'region': None},
    'Kraków': {'isRemote': 0, 'city': 'Krakow', 'state': None, 'country': 'Poland', 'region': None},
    'London - (hybrid working options available)': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'London, United Kingdom': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'London, England, United Kingdom': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'London (with hybrid working options available)': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'London (with hybrid working available)': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'London': {'isRemote': 0, 'city': 'London', 'state': None, 'country': 'UK', 'region': None},
    'Los Altos': {'isRemote': 0, 'city': 'Los Altos', 'state': 'California', 'country': 'USA', 'region': None},
    'Los Angeles, California': {'isRemote': 0, 'city': 'Los Angeles', 'state': 'California', 'country': 'USA', 'region': None},
    'Los Angeles, CA': {'isRemote': 0, 'city': 'Los Angeles', 'state': 'California', 'country': 'USA', 'region': None},
    'Century City': {'isRemote': 0, 'city': 'Los Angeles', 'state': 'California', 'country': 'USA', 'region': None},
    'Los Angeles, California, United States': {'isRemote': 0, 'city': 'Los Angeles', 'state': 'California', 'country': 'USA', 'region': None},
    'Melbourne': {'isRemote': 0, 'city': 'Melbourne', 'state': None, 'country': 'Australia', 'region': None},
    'Remote - Melbourne': {'isRemote': 1, 'city': 'Melbourne', 'state': None, 'country': 'Australia', 'region': 'Melbourne'},
    'Mendota Heights, Minnesota': {'isRemote': 0, 'city': 'Mendota Heights', 'state': 'Minnesota', 'country': 'USA', 'region': None},
    'Miami, Florida, United States': {'isRemote': 0, 'city': 'Miami', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Miami, Florida': {'isRemote': 0, 'city': 'Miami', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Miami': {'isRemote': 0, 'city': 'Miami', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Milwaukee, WI': {'isRemote': 0, 'city': 'Milwaukee', 'state': 'California', 'country': 'USA', 'region': None},
    'Montevideo': {'isRemote': 0, 'city': 'Montevideo', 'state': None, 'country': 'Uruguay', 'region': None},
    'Montreal, Quebec': {'isRemote': 0, 'city': 'Montreal', 'state': 'Quebec', 'country': 'Canada', 'region': None},
    'Moscow, Russia': {'isRemote': 0, 'city': 'Moscow', 'state': None, 'country': 'Russia', 'region': None},
    'Nashville, TN': {'isRemote': 0, 'city': 'Nashville', 'state': 'Tennessee', 'country': 'USA', 'region': None},
    'nashville, TN': {'isRemote': 0, 'city': 'Nashville', 'state': 'Tennessee', 'country': 'USA', 'region': None},
    'New York, New York, United States': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'Brooklyn': {'isRemote': 0, 'city': 'Brooklyn', 'state': 'New York', 'country': 'USA', 'region': None},
    'quip NYC': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York, New York': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York City, New York': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York, NY': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York City': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'Manhattan, New York, United States': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York, USA': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'New York City, NY': {'isRemote': 0, 'city': 'New York', 'state': 'New York', 'country': 'USA', 'region': None},
    'Newark, New Jersey': {'isRemote': 0, 'city': 'Newark', 'state': 'New Jersey', 'country': 'USA', 'region': None},
    'Newtown, CT': {'isRemote': 0, 'city': 'Newton', 'state': 'Connecticut', 'country': 'USA', 'region': None},
    'Norfolk, Virginia': {'isRemote': 0, 'city': 'Norfolk', 'state': 'Virginia', 'country': 'USA', 'region': None},
    'Nottingham': {'isRemote': 0, 'city': 'Nottingham', 'state': None, 'country': 'UK', 'region': None},
    'Orlando': {'isRemote': 0, 'city': 'Orlando', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Orlando, Florida': {'isRemote': 0, 'city': 'Orlando', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Orlando, USA': {'isRemote': 0, 'city': 'Orlando', 'state': 'Florida', 'country': 'USA', 'region': None},
    'Perth': {'isRemote': 0, 'city': 'Perth', 'state': None, 'country': 'Australia', 'region': None},
    'Philadelphia, Pennsylvania': {'isRemote': 0, 'city': 'Philadelphia', 'state': 'Pennsylvania', 'country': None, 'region': None},
    'Philidelphia, PA': {'isRemote': 0, 'city': 'Phildelphia', 'state': 'Pennsylvania', 'country': 'USA', 'region': None},
    'Phoenix, Arizona': {'isRemote': 0, 'city': 'Phoenix', 'state': 'Arizona', 'country': 'USA', 'region': None},
    'Pittsburgh, Pennsylvania': {'isRemote': 0, 'city': 'Pittsburgh', 'state': 'Pennsylvania', 'country': 'USA', 'region': None},
    'Princeton': {'isRemote': 0, 'city': 'Princeton', 'state': 'New Jersey', 'country': 'USA', 'region': None},
    'Providence, Rhode Island': {'isRemote': 0, 'city': 'Providence', 'state': 'Rhode Island', 'country': 'USA', 'region': None},
    'Redwood City, California, United States': {'isRemote': 0, 'city': 'Redwood City', 'state': 'California', 'country': 'USA', 'region': None},
    'San Antonio, Texas': {'isRemote': 0, 'city': 'San Antonio', 'state': 'Texas', 'country': 'USA', 'region': None},
    'San Diego, California': {'isRemote': 0, 'city': 'San Diego', 'state': 'California', 'country': 'USA', 'region': None},
    'San Diego, CA': {'isRemote': 0, 'city': 'San Diego', 'state': 'California', 'country': 'USA', 'region': None},
    'San Francisco, California': {'isRemote': 0, 'city': 'San Francisco', 'state': 'California', 'country': None, 'region': None},
    'San Francisco Bay Area': {'isRemote': 0, 'city': 'San Francisco', 'state': 'California', 'country': 'USA', 'region': None},
    'San Francisco': {'isRemote': 0, 'city': 'San Francisco', 'state': 'California', 'country': 'USA', 'region': None},
    'San Francisco, CA': {'isRemote': 0, 'city': 'San Francisco', 'state': 'California', 'country': 'USA', 'region': None},
    'San Francisco, California, United States': {'isRemote': 0, 'city': 'San Francisco', 'state': 'California', 'country': 'USA', 'region': None},
    'San Jose, California': {'isRemote': 0, 'city': 'San Jose', 'state': 'California', 'country': 'USA', 'region': None},
    'Savannah, Georgia': {'isRemote': 0, 'city': 'Savannah', 'state': 'Georgia', 'country': 'USA', 'region': None},
    'Schaumburg, Illinois': {'isRemote': 0, 'city': 'Schaumburg', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Seattle, Washington, United States': {'isRemote': 0, 'city': 'Seattle', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Seattle, Washington': {'isRemote': 0, 'city': 'Seattle', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Seattle': {'isRemote': 0, 'city': 'Seattle', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Seattle, WA': {'isRemote': 0, 'city': 'Seattle', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Gangnam-gu, Seoul, South Korea': {'isRemote': 0, 'city': 'Seoul', 'state': None, 'country': 'South Korea', 'region': None},
    'St. Louis': {'isRemote': 0, 'city': 'St. Louis', 'state': 'Missouri', 'country': 'USA', 'region': None},
    'St. Louis, Missouri': {'isRemote': 0, 'city': 'St. Louis', 'state': 'Missouri', 'country': 'USA', 'region': None},
    'Stockholm, Sweden': {'isRemote': 0, 'city': 'Stockholm', 'state': None, 'country': 'Sweden', 'region': None},
    'Swansea, IL': {'isRemote': 0, 'city': 'Swansea', 'state': 'Illinois', 'country': 'USA', 'region': None},
    'Sydney': {'isRemote': 0, 'city': 'Sydney', 'state': None, 'country': 'Australia', 'region': None},
    'Toronto, ON': {'isRemote': 0, 'city': 'Toronto', 'state': 'Ontario', 'country': 'Canada', 'region': None},
    'Toronto, Ontario': {'isRemote': 0, 'city': 'Toronto', 'state': 'Ontario', 'country': 'Canada', 'region': None},
    'Greater Toronto Area, ON': {'isRemote': 0, 'city': 'Toronto', 'state': 'Ontario', 'country': 'Canada', 'region': None},
    'Tucson, Arizona': {'isRemote': 0, 'city': 'Tucson', 'state': 'Arizona', 'country': 'USA', 'region': None},
    'Vancouver, Washington': {'isRemote': 0, 'city': 'Vancouver', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Vancouver, British Columbia': {'isRemote': 0, 'city': 'Vancouver', 'state': 'British Columbia', 'country': 'Canada', 'region': None},
    'Vancouver, WA': {'isRemote': 0, 'city': 'Vancouver', 'state': 'Washington', 'country': 'USA', 'region': None},
    'Vancouver, BC': {'isRemote': 0, 'city': 'Vancouver', 'state': 'British Columbia', 'country': 'Canada', 'region': None},
    'Washington, District of Columbia, United States': {'isRemote': 0, 'city': 'Washington', 'state': 'DC', 'country': 'USA', 'region': None},
    'Washington, D.C.': {'isRemote': 0, 'city': 'Washington', 'state': 'DC', 'country': 'USA', 'region': None},
    'Washington, DC': {'isRemote': 0, 'city': 'Washington', 'state': 'DC', 'country': 'USA', 'region': None},
    'Yerevan': {'isRemote': 0, 'city': 'Yerevan', 'state': None, 'country': 'Romania', 'region': None},
    'Remote (EU)': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'EU'},
    'Remote - Canada': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Canada', 'region': 'Canada'},
    'US Home-based (Colorado, Delaware, Virginia)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'Colorado, Delaware, Virginia'},
    'Remote - Czech Republic': {'isRemote': 0, 'city': None, 'state': None, 'country': 'Czech Republic', 'region': None},
    'Remote first with occasional travel to Liberis London/Nottingham': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
    'Remote (within United States)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Remote - Indonesia': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Indonesia', 'region': 'Indonesia'},
    'Remote, California': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'California'},
    'MOLOCO APAC': {'isRemote': 0, 'city': None, 'state': None, 'country': None, 'region': 'Uknown'},
    'Singapore': {'isRemote': 0, 'city': None, 'state': None, 'country': 'Singapore', 'region': None},
    'Anywhere': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
    'Denver or Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'USA'},
    'Finland': {'isRemote': 0, 'city': None, 'state': None, 'country': 'Finland', 'region': None},
    'US Home-based (flexible on location)': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'USA'},
    'REMOTE': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
    'USA - West Coast': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'West coast'},
    'India (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'India', 'region': 'India'},
    'Remote - South Korea': {'isRemote': 1, 'city': None, 'state': None, 'country': 'South Korea', 'region': 'South Korea'},
    'Spain (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Spain', 'region': 'Spain'},
    'Remote- United States': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Remote - Ecuador': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Ecuador', 'region': 'Ecuador'},
    'USA Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Singapore, Central Singapore, Singapore': {'isRemote': 0, 'city': None, 'state': 'Central Singapore', 'country': 'Singapore', 'region': None},
    'Remote - Poland': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Poland', 'region': 'Poland'},
    'United States': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Denver, Atlanta, or Chicago (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'Denver, Atlanta, Chicago'},
    'Remote, New York Office or Charlotte Office': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Germany (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Germany', 'region': 'Germany'},
    'China': {'isRemote': 1, 'city': None, 'state': None, 'country': 'China', 'region': 'China'},
    'United States - East Coast Preferred': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'East coast'},
    'Worldwide': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
    'London or Nottingham (UK Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'APAC Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'APAC'},
    'United States (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'New York OR Remote - United States': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'India, India': {'isRemote': 1, 'city': None, 'state': None, 'country': 'India', 'region': 'India'},
    'Remote or San Francisco, California': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'London, Nottingham, Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Remote - Paris': {'isRemote': 1, 'city': None, 'state': None, 'country': 'France', 'region': 'Paris'},
    'Remote - Germany': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Germany', 'region': 'Germany'},
    'London or Nottingham (Hybrid or UK Remote available)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Remote - United States': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'US': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'West Coast Hours': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'West coast'},
    'London, Nottingham, Hybrid': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Remote - India': {'isRemote': 1, 'city': None, 'state': None, 'country': 'India', 'region': 'India'},
    'UK remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'UK'},
    'USA': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'London & Nottingham (Hybrid and UK Remote available)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Northeast, USA': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'Northeast'},
    'France (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'France', 'region': 'France'},
    'Remote - Berlin': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Germany', 'region': 'Berlin'},
    'Denver, CO or Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'London or Nottingham (with hybrid or UK remote available)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Canada': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Canada', 'region': 'Canada'},
    'Remote - Uruguay': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Uruguay', 'region': 'Uruguay'},
    'Remote - US': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Netherlands (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Netherlands', 'region': 'Netherlands'},
    'London or Nottingham (Hybrid working available)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'Remote - Spain': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Spain', 'region': 'Spain'},
    'Singapore (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Singapore', 'region': 'Singapore'},
    'India': {'isRemote': 1, 'city': None, 'state': None, 'country': 'India', 'region': 'India'},
    'Australia (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Australia', 'region': 'Australia'},
    'Japan': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Japan', 'region': 'Japan'},
    'United Kingdom (Remote)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'UK'},
    'Remote - Romania': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Romania', 'region': 'Romania'},
    'Remote - Vietnam': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Vietnam', 'region': 'Vietnam'},
    'Florida': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'Florida'},
    'MOLOCO America': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
    'Remote - France': {'isRemote': 1, 'city': None, 'state': None, 'country': 'France', 'region': 'France'},
    'Washington DC, Los Altos, Miami, San Francisco, Seattle': {'isRemote': 0, 'city': None, 'state': None, 'country': None, 'region': 'Washington DC, Los Altos, Miami, San Francisco, Seattle'},
    'Remote - Peru': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Peru', 'region': 'Peru'},
    'Remote - Colombia': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Colombia', 'region': 'Colombia'},
    'New York/Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'San Francisco, Nashville': {'isRemote': 0, 'city': None, 'state': None, 'country': None, 'region': 'San Francisco, Nashville'},
    'US Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'HQ/Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': None},
    'London or Nottingham (with UK remote or hybrid working available)': {'isRemote': 1, 'city': None, 'state': None, 'country': 'UK', 'region': 'London, Nottingham'},
    'North America': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'North America'},
    'Remote - Malaysia': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Malaysia', 'region': 'Malaysia'},
    'Europe': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'Europe'},
    'Denver & Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': 'USA', 'region': 'USA'},
    'Los Angeles, California, United States, San Francisco, California, United States': {'isRemote': 0, 'city': None, 'state': 'California', 'country': 'USA', 'region': 'Los Angeles, San Francisco'},
    'Mexico': {'isRemote': 1, 'city': None, 'state': None, 'country': 'Mexico', 'region': 'Mexico'},
    'EU Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': 'EU'},
    'New York City, Poland or Remote': {'isRemote': 1, 'city': None, 'state': None, 'country': None, 'region': None},
}

COMMON = {
    # US
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
    'United States': 'USA',
    'United States of America': 'USA',
    'US': 'USA',
    'District of Columbia': 'DC',
    'New York City': 'New York',
    'NYC': 'New York',
    # Canada
    'ON': 'Ontario',

    # Other
    'United Kingdom': 'UK',
}
